### PR TITLE
Improving reading a file + snagging templates (i.e. `pretty janky, but we want this whitespace to be reflected in the component.`).

### PR DESCRIPTION
**Pull request by mini-eggs**
There were
```javascript
// pretty janky, but we want this whitespace to be reflected in the component.
```

in the code throughout the components folder. I removed this while implementing a better way to make template files. See template directory. Lemme know what you're thinking. 👍

### CODE REVIEW

**Comment by hanford** [comment]
wow @mini-eggs this is great!

I think I would slightly prefer no utilities file, and the stateful functions grabbing and reading them to be in the `components/X` file.

Thoughts?

**Comment by mini-eggs** [comment]
Haha ty 😄, and thanks for the lib!

@hanford I'll agree with that.

I'll move getStyles/getTest/getIndex functions into components/x and make a file called get-template to house the getTemplate function.

That work for you?

**Comment by hanford** [comment]
Awesome, thanks! Sounds good, I'll merge after your update

**Comment by mini-eggs** [comment]
Should be golden!

**Comment by hanford** [comment]
Thanks @mini-eggs !

**Pull request merged**
