### PR TITLE
New features + refactoring

### PR DESCRIPTION
**Pull request by varya**
* Fixed --redux parameter (now it's according to documentation)

* Refactoring. Now there is `config.js` file with default configuration, and all the CLI options change the configuration. Then, it is generated according to the resultant configuration.

* User can provide their own configuration. Example here https://github.com/SC5/ds-workshop-storybook-boilerplate/tree/create-component-cli/.add-component

* Added storybook generator
* Added styled-component generator

### CODE REVIEW

**Comment by hanford** [comment]
Cool, briefly looked and this looks good. I'll write some more feedback tomorrow. (some console.logs we'll want to remove, and some other things) .. overall this is exciting!

**Review by hanford — COMMENTED** [review]
On mobile again, I guess one of the other things I’d prefer is disabling styled-component generation (and css if it’s, don’t remember) and storybook, by default.. and have them be opt in via a flag thoughts?

**Comment by hanford** [comment]
Also, seriously great PR! Really appreciate 🙌

**Comment by varya** [comment]
Thanks. I will update tomorrow then.

**Comment by varya** [comment]
@hanford 

Fixed. How it works now:

```

  𝒟ℴ ./node_modules/add-component/index.js Example
Component Example created

  𝒟ℴ ls Example/
Example.js      Example.test.js index.js
```

```
  𝒟ℴ ./node_modules/add-component/index.js Example -c
Component Example created
  𝒟ℴ ls Example/
Example.js      Example.test.js index.js        style.css
```

```
  𝒟ℴ ./node_modules/add-component/index.js Example -c styled-components
Component Example created
  𝒟ℴ ls Example/
Example.js      Example.test.js index.js        styles.js
```

```
  𝒟ℴ ./node_modules/add-component/index.js Example --config ./.add-component/config.js
Component Example created
  𝒟ℴ ls src/Example/
Example.stories.js Example.test.js    index.js           styles.js
```

```
  𝒟ℴ ./node_modules/add-component/index.js Example --config ./.add-component/config.js -c css
Component Example created
  𝒟ℴ ls src/Example/
Example.stories.js Example.test.js    index.js           style.css
```

So, configuration changes the default settings but the CLI can overwrite it.

**Comment by hanford** [comment]
Live as of `2.4.0` thanks again! I'm excited to have some new life in this plugin. If you continue making contributions like this I'll give you commit access!

**Comment by varya** [comment]
@hanford Thanks! Yes, I would like to contribute more.
We've already used this in out company in-house workshop on React. For the people who a new to the React eco system, it is much easier to create the files with one tool. People were happy about such helping add-on but I noticed some things that can be improved, so I will continue to provide changes.

**Pull request merged**
